### ISSUE TITLE
[Help] blacklist for filetype

### ISSUE THREAD

**Issue by roachsinai** [inkarkat/vim-ShowTrailingWhitespace#2]
```
The default filter also checks two blacklists:
- *g:ShowTrailingWhitespace_Blacklist* (valid for the current Vim session)
- *g:SHOWTRAILINGWHITESPACE_BLACKLIST* (persisted across Vim sessions)
You can define your own commands or mappings to add or remove the current file
to that blacklist: >
    command! -bar ShowTrailingWhitespaceBlacklistForSession  call ShowTrailingWhitespace#Filter#BlacklistFile(0)
    command! -bar ShowTrailingWhitespaceBlacklistPermanently call ShowTrailingWhitespace#Filter#BlacklistFile(1)
    command! -bar ShowTrailingWhitespaceBlacklistRemoveFile  call ShowTrailingWhitespace#Filter#RemoveFileFromBlacklist()
```

I tried run `call ShowTrailingWhitespace#Filter#BlacklistFile(0)` seems it put the current file name to `g:ShowTrailingWhitespace_Blacklist`.

---

And I wanna know how to block a filetype? Thanks in advance!

**Comment by inkarkat** [comment]
> I tried run call `ShowTrailingWhitespace#Filter#BlacklistFile(0)` seems it put the current file name to `g:ShowTrailingWhitespace_Blacklist.`

Yes, that's correct. The non-uppercased variable is for the current session.

> And I wanna know how to block a filetype?

Put the following in a file named e.g. `ftplugin/{filetype}_ShowTrailingWhitespace.vim`:

    if ShowTrailingWhitespace#IsSet()
	    call ShowTrailingWhitespace#Set(0,0)
    endif

You could also use the generic `g:ShowTrailingWhitespace_FilterFunc`, but I think it's more straightforward to build upon Vim's existing filetype-plugin functionality.

PS: This information was a bit hidden inside the documentation, I've expanded and restructured that part. Thank you for your feedback!
