### ISSUE TITLE
Unknown function?

### ISSUE THREAD

**Issue by taw00** [inkarkat/vim-ShowTrailingWhitespace#8]
Note, I used vim-plug to install this plugin...

```
Error detected while processing /home/todd/.vim/plugged/vim-ShowTrailingWhitespace/plugin/ShowTrailingWhitespace.vim[60]..function ShowTrailingWhitespace#Color#EnsureVisibleBackgroundColor[1]..<SNR>28_HasVisibleBackground:
line    1:
E117: Unknown function: ingo#hlgroup#GetApplicableColorModes
```

**Comment by inkarkat** [comment]
You also need to install the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or likely via [GitHub](https://github.com/inkarkat/vim-ingo-library) as you're using _vim-plug_). It's listed in the [dependencies](https://github.com/inkarkat/vim-ShowTrailingWhitespace#dependencies). This library contains common autoload functions that are used by almost all of my plugins; it avoids code duplication and versioning issues. Prior to the current version 1.12 this used to be an optional dependency; now it's mandatory.
